### ISSUE TITLE
ROS 2: find_package doesn't populate the INCLUDE_DIRS variable as expected

### ISSUE THREAD

**Issue by Martin-Idel-SI** [ros/resource_retriever#21]
In RViz2, we're using resource_retriever as a dependency. When doing a `find_package(resource_retriever REQUIRED)` I would have expected the variable `resource_retriever_INCLUDE_DIRS` to contain the path to the include files of resource retriever and its dependencies.

However, it only contains the paths to the includes of its dependencies (in an isolated build, e.g. ` <path_to_ros2>/install_isolated/ament_index_cpp/include;/usr/include/x86_64-linux-gnu`). Is this expected behaviour? If yes, how do I get the correct include paths for building static and object libraries? 

Background: When building all rviz2 libraries dynamically, everything works fine (I don't quite understand how, but `ament_export_interfaces` seems to play a role), but in order to have tests for its default plugins, I want to build a static library of `rviz_default_plugins` as well - at that point, ament can't find the correct includes of `resource_retriever` anymore.

**Comment by clalancette** [comment]
Briefly looking at it, I think the ROS2 `CMakeLists.txt` is probably missing an `ament_export_include_directories(include)`.  @Martin-Idel-SI , could you try adding that around [Line 37](https://github.com/ros/resource_retriever/blob/ros2/resource_retriever/CMakeLists.txt#L37), and see if that helps?

**Comment by Martin-Idel-SI** [comment]
@clalancette Yes, that's enough to solve my problem. It would be nice if that could be added, thanks!

**Comment by clalancette** [comment]
https://github.com/ros/resource_retriever/pull/22 should do it.  Thanks for testing.

**Comment by mikaelarguedas** [comment]
I believe this can be closed now that #22 has merged

**Comment by clalancette** [comment]
> I believe this can be closed now that #22 has merged

Yeah, definitely.  Not sure why GitHub didn't close this out, but doing so by hand now.
