### ISSUE TITLE
next bloom schedule?

### ISSUE THREAD

**Issue by JaehyunShim** [ros/resource_retriever#59]
Hi, 

When is the next bloom schedule with the newly added [retriever.hpp](https://github.com/ros/resource_retriever/blob/ros2/resource_retriever/include/resource_retriever/retriever.hpp)?

Thanks! 
Jaehyun

**Comment by clalancette** [comment]
It was already released into Rolling back in December: https://github.com/ros/rosdistro/pull/27673

**Comment by JaehyunShim** [comment]
@clalancette 
Thanks!

**Comment by JaehyunShim** [comment]
@clalancette 

sorry, I checked it again and it seems the .hpp header file wasn't added to the foxy branch (?) when you released the foxy distro. See the below link.
https://github.com/ros/resource_retriever/tree/foxy/resource_retriever/include/resource_retriever

**Comment by clalancette** [comment]
> sorry, I checked it again and it seems the .hpp header file wasn't added to the foxy branch (?) when you released the foxy distro. See the below link.

Yes, that's correct.  Changing the header file is a break for the downstream users, so we only put it in the rolling branch, not foxy.

**Comment by JaehyunShim** [comment]
@clalancette  ok thanks !
