### ISSUE TITLE
Unknown CMake command "fail".

### ISSUE THREAD

**Issue by hiepcdt4** [ros/resource_retriever#61]
When trying to compile using ROS melodic

It fails with the following:

-- +++ processing catkin package: 'resource_retriever'
-- ==> add_subdirectory(actual_device/sick_line_mlse/resource_retriever-1.12.6)
-- Boost version: 1.65.1
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CURL not found!  Aborting...
CMake Error at actual_device/sick_line_mlse/resource_retriever-1.12.6/CMakeLists.txt:13 (fail):
  Unknown CMake command "fail".

-- Configuring incomplete, errors occurred!
See also "/root/Kit_AGV_ws/build/CMakeFiles/CMakeOutput.log".
See also "/root/Kit_AGV_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by clalancette** [comment]
Do you have `libcurl4-openssl-dev` installed?

In the future, please ask questions like this on https://answers.ros.org, which is our central place for questions and answers.  I'm going to close this out.
