### ISSUE TITLE
 retriever.h missing from foxy

### ISSUE THREAD

**Issue by brennand** [ros/resource_retriever#65]
The deprecate header:  `retriever.h`  is in galaxy but missing from foxy branch.

[https://github.com/ros/resource_retriever/pull/51](url)

**Comment by clalancette** [comment]
It doesn't look like it to me:

* Foxy branch: https://github.com/ros/resource_retriever/tree/foxy/resource_retriever/include/resource_retriever (contains retriever.h only)
* Galactic branch: https://github.com/ros/resource_retriever/tree/galactic/resource_retriever/include/resource_retriever (contains both retriever.h and retriever.hpp)
* ROS 2 branch (development): https://github.com/ros/resource_retriever/tree/ros2/resource_retriever/include/resource_retriever (contains only retriever.hpp)

As far as I can tell, that is what is intended; the `.h` file is in Foxy, it was deprecated (but still available) in Galactic, and now it is removed from development (which will eventually become Humble).

I'm going to close this out, but feel free to reopen if this doesn't make sense or you still think there is a problem here.
